// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: account_manager.sql

package dbgen

import (
	"context"
)

const deleteAccountManager = `-- name: DeleteAccountManager :exec
DELETE FROM account_manager WHERE company_id = ? AND agent_id = ?
`

type DeleteAccountManagerParams struct {
	CompanyID int64 `json:"company_id"`
	AgentID   int64 `json:"agent_id"`
}

func (q *Queries) DeleteAccountManager(ctx context.Context, arg DeleteAccountManagerParams) error {
	_, err := q.db.ExecContext(ctx, deleteAccountManager, arg.CompanyID, arg.AgentID)
	return err
}

const insertAccountManager = `-- name: InsertAccountManager :exec
INSERT OR IGNORE INTO account_manager (company_id, agent_id) VALUES (?, ?)
`

type InsertAccountManagerParams struct {
	CompanyID int64 `json:"company_id"`
	AgentID   int64 `json:"agent_id"`
}

func (q *Queries) InsertAccountManager(ctx context.Context, arg InsertAccountManagerParams) error {
	_, err := q.db.ExecContext(ctx, insertAccountManager, arg.CompanyID, arg.AgentID)
	return err
}

const listAccountManagers = `-- name: ListAccountManagers :many
SELECT company_id, agent_id, created_at FROM account_manager ORDER BY company_id, agent_id
`

func (q *Queries) ListAccountManagers(ctx context.Context) ([]AccountManager, error) {
	rows, err := q.db.QueryContext(ctx, listAccountManagers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AccountManager{}
	for rows.Next() {
		var i AccountManager
		if err := rows.Scan(&i.CompanyID, &i.AgentID, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAccountManagersByCompany = `-- name: ListAccountManagersByCompany :many
SELECT company_id, agent_id, created_at FROM account_manager WHERE company_id = ? ORDER BY agent_id
`

func (q *Queries) ListAccountManagersByCompany(ctx context.Context, companyID int64) ([]AccountManager, error) {
	rows, err := q.db.QueryContext(ctx, listAccountManagersByCompany, companyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AccountManager{}
	for rows.Next() {
		var i AccountManager
		if err := rows.Scan(&i.CompanyID, &i.AgentID, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
