// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: cache.sql

package dbgen

import (
	"context"
)

const deleteAllCache = `-- name: DeleteAllCache :exec
DELETE FROM api_cache
`

func (q *Queries) DeleteAllCache(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteAllCache)
	return err
}

const deleteCache = `-- name: DeleteCache :exec
DELETE FROM api_cache WHERE cache_key = ?
`

func (q *Queries) DeleteCache(ctx context.Context, cacheKey string) error {
	_, err := q.db.ExecContext(ctx, deleteCache, cacheKey)
	return err
}

const deleteExpiredCache = `-- name: DeleteExpiredCache :exec
DELETE FROM api_cache WHERE datetime(cached_at, '+' || max_age_secs || ' seconds') < datetime('now')
`

func (q *Queries) DeleteExpiredCache(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteExpiredCache)
	return err
}

const getCache = `-- name: GetCache :one
SELECT cache_key, response_body, etag, cached_at, max_age_secs FROM api_cache WHERE cache_key = ?
`

func (q *Queries) GetCache(ctx context.Context, cacheKey string) (ApiCache, error) {
	row := q.db.QueryRowContext(ctx, getCache, cacheKey)
	var i ApiCache
	err := row.Scan(
		&i.CacheKey,
		&i.ResponseBody,
		&i.Etag,
		&i.CachedAt,
		&i.MaxAgeSecs,
	)
	return i, err
}

const setCache = `-- name: SetCache :exec
INSERT INTO api_cache (cache_key, response_body, etag, cached_at, max_age_secs)
VALUES (?, ?, ?, ?, ?)
ON CONFLICT(cache_key) DO UPDATE SET
    response_body = excluded.response_body,
    etag = excluded.etag,
    cached_at = excluded.cached_at,
    max_age_secs = excluded.max_age_secs
`

type SetCacheParams struct {
	CacheKey     string  `json:"cache_key"`
	ResponseBody string  `json:"response_body"`
	Etag         *string `json:"etag"`
	CachedAt     string  `json:"cached_at"`
	MaxAgeSecs   int64   `json:"max_age_secs"`
}

func (q *Queries) SetCache(ctx context.Context, arg SetCacheParams) error {
	_, err := q.db.ExecContext(ctx, setCache,
		arg.CacheKey,
		arg.ResponseBody,
		arg.Etag,
		arg.CachedAt,
		arg.MaxAgeSecs,
	)
	return err
}
