// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: config.sql

package dbgen

import (
	"context"
)

const deleteConfig = `-- name: DeleteConfig :exec
DELETE FROM config WHERE key = ?
`

func (q *Queries) DeleteConfig(ctx context.Context, key string) error {
	_, err := q.db.ExecContext(ctx, deleteConfig, key)
	return err
}

const getConfig = `-- name: GetConfig :one
SELECT "key", value, description, updated_at FROM config WHERE key = ?
`

func (q *Queries) GetConfig(ctx context.Context, key string) (Config, error) {
	row := q.db.QueryRowContext(ctx, getConfig, key)
	var i Config
	err := row.Scan(
		&i.Key,
		&i.Value,
		&i.Description,
		&i.UpdatedAt,
	)
	return i, err
}

const listConfig = `-- name: ListConfig :many
SELECT "key", value, description, updated_at FROM config ORDER BY key
`

func (q *Queries) ListConfig(ctx context.Context) ([]Config, error) {
	rows, err := q.db.QueryContext(ctx, listConfig)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Config{}
	for rows.Next() {
		var i Config
		if err := rows.Scan(
			&i.Key,
			&i.Value,
			&i.Description,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertConfig = `-- name: UpsertConfig :exec
INSERT INTO config (key, value, description, updated_at)
VALUES (?, ?, ?, datetime('now'))
ON CONFLICT(key) DO UPDATE SET
    value = excluded.value,
    description = excluded.description,
    updated_at = excluded.updated_at
`

type UpsertConfigParams struct {
	Key         string `json:"key"`
	Value       string `json:"value"`
	Description string `json:"description"`
}

func (q *Queries) UpsertConfig(ctx context.Context, arg UpsertConfigParams) error {
	_, err := q.db.ExecContext(ctx, upsertConfig, arg.Key, arg.Value, arg.Description)
	return err
}
