// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package dbgen

import (
	"time"
)

type AccountManager struct {
	CompanyID int64  `json:"company_id"`
	AgentID   int64  `json:"agent_id"`
	CreatedAt string `json:"created_at"`
}

type ApiCache struct {
	CacheKey     string  `json:"cache_key"`
	ResponseBody string  `json:"response_body"`
	Etag         *string `json:"etag"`
	CachedAt     string  `json:"cached_at"`
	MaxAgeSecs   int64   `json:"max_age_secs"`
}

type Config struct {
	Key         string `json:"key"`
	Value       string `json:"value"`
	Description string `json:"description"`
	UpdatedAt   string `json:"updated_at"`
}

type Migration struct {
	MigrationNumber int64      `json:"migration_number"`
	MigrationName   string     `json:"migration_name"`
	ExecutedAt      *time.Time `json:"executed_at"`
}

type SprintAnchor struct {
	SprintNumber int64  `json:"sprint_number"`
	Year         int64  `json:"year"`
	StartDate    string `json:"start_date"`
}

type TicketState struct {
	TicketID    int64   `json:"ticket_id"`
	Priority    int64   `json:"priority"`
	Blocked     int64   `json:"blocked"`
	Note        string  `json:"note"`
	ReviewAfter *string `json:"review_after"`
	Today       int64   `json:"today"`
	UpdatedAt   string  `json:"updated_at"`
	DeferredAt  *string `json:"deferred_at"`
}
