// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sprint_anchor.sql

package dbgen

import (
	"context"
)

const deleteSprintAnchor = `-- name: DeleteSprintAnchor :exec
DELETE FROM sprint_anchor WHERE year = ? AND sprint_number = ?
`

type DeleteSprintAnchorParams struct {
	Year         int64 `json:"year"`
	SprintNumber int64 `json:"sprint_number"`
}

func (q *Queries) DeleteSprintAnchor(ctx context.Context, arg DeleteSprintAnchorParams) error {
	_, err := q.db.ExecContext(ctx, deleteSprintAnchor, arg.Year, arg.SprintNumber)
	return err
}

const getSprintAnchorsForYear = `-- name: GetSprintAnchorsForYear :many
SELECT sprint_number, year, start_date FROM sprint_anchor WHERE year = ? ORDER BY sprint_number ASC
`

func (q *Queries) GetSprintAnchorsForYear(ctx context.Context, year int64) ([]SprintAnchor, error) {
	rows, err := q.db.QueryContext(ctx, getSprintAnchorsForYear, year)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SprintAnchor{}
	for rows.Next() {
		var i SprintAnchor
		if err := rows.Scan(&i.SprintNumber, &i.Year, &i.StartDate); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSprintAnchors = `-- name: ListSprintAnchors :many
SELECT sprint_number, year, start_date FROM sprint_anchor ORDER BY year DESC, sprint_number ASC
`

func (q *Queries) ListSprintAnchors(ctx context.Context) ([]SprintAnchor, error) {
	rows, err := q.db.QueryContext(ctx, listSprintAnchors)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SprintAnchor{}
	for rows.Next() {
		var i SprintAnchor
		if err := rows.Scan(&i.SprintNumber, &i.Year, &i.StartDate); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertSprintAnchor = `-- name: UpsertSprintAnchor :exec
INSERT INTO sprint_anchor (sprint_number, year, start_date)
VALUES (?, ?, ?)
ON CONFLICT(year, sprint_number) DO UPDATE SET
    start_date = excluded.start_date
`

type UpsertSprintAnchorParams struct {
	SprintNumber int64  `json:"sprint_number"`
	Year         int64  `json:"year"`
	StartDate    string `json:"start_date"`
}

func (q *Queries) UpsertSprintAnchor(ctx context.Context, arg UpsertSprintAnchorParams) error {
	_, err := q.db.ExecContext(ctx, upsertSprintAnchor, arg.SprintNumber, arg.Year, arg.StartDate)
	return err
}
