// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: ticket_state.sql

package dbgen

import (
	"context"
)

const deleteTicketState = `-- name: DeleteTicketState :exec
DELETE FROM ticket_state WHERE ticket_id = ?
`

func (q *Queries) DeleteTicketState(ctx context.Context, ticketID int64) error {
	_, err := q.db.ExecContext(ctx, deleteTicketState, ticketID)
	return err
}

const getTicketState = `-- name: GetTicketState :one
SELECT ticket_id, priority, blocked, note, review_after, today, updated_at FROM ticket_state WHERE ticket_id = ?
`

func (q *Queries) GetTicketState(ctx context.Context, ticketID int64) (TicketState, error) {
	row := q.db.QueryRowContext(ctx, getTicketState, ticketID)
	var i TicketState
	err := row.Scan(
		&i.TicketID,
		&i.Priority,
		&i.Blocked,
		&i.Note,
		&i.ReviewAfter,
		&i.Today,
		&i.UpdatedAt,
	)
	return i, err
}

const listTicketStates = `-- name: ListTicketStates :many
SELECT ticket_id, priority, blocked, note, review_after, today, updated_at FROM ticket_state ORDER BY priority DESC, updated_at DESC
`

func (q *Queries) ListTicketStates(ctx context.Context) ([]TicketState, error) {
	rows, err := q.db.QueryContext(ctx, listTicketStates)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TicketState{}
	for rows.Next() {
		var i TicketState
		if err := rows.Scan(
			&i.TicketID,
			&i.Priority,
			&i.Blocked,
			&i.Note,
			&i.ReviewAfter,
			&i.Today,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTodayTicketStates = `-- name: ListTodayTicketStates :many
SELECT ticket_id, priority, blocked, note, review_after, today, updated_at FROM ticket_state WHERE today = 1 ORDER BY priority DESC
`

func (q *Queries) ListTodayTicketStates(ctx context.Context) ([]TicketState, error) {
	rows, err := q.db.QueryContext(ctx, listTodayTicketStates)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TicketState{}
	for rows.Next() {
		var i TicketState
		if err := rows.Scan(
			&i.TicketID,
			&i.Priority,
			&i.Blocked,
			&i.Note,
			&i.ReviewAfter,
			&i.Today,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTriageableTicketIDs = `-- name: ListTriageableTicketIDs :many
SELECT ticket_id FROM ticket_state WHERE priority = 0 AND today = 0 AND blocked = 0
`

func (q *Queries) ListTriageableTicketIDs(ctx context.Context) ([]int64, error) {
	rows, err := q.db.QueryContext(ctx, listTriageableTicketIDs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var ticket_id int64
		if err := rows.Scan(&ticket_id); err != nil {
			return nil, err
		}
		items = append(items, ticket_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertTicketState = `-- name: UpsertTicketState :exec
INSERT INTO ticket_state (ticket_id, priority, blocked, note, review_after, today, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(ticket_id) DO UPDATE SET
    priority = excluded.priority,
    blocked = excluded.blocked,
    note = excluded.note,
    review_after = excluded.review_after,
    today = excluded.today,
    updated_at = excluded.updated_at
`

type UpsertTicketStateParams struct {
	TicketID    int64   `json:"ticket_id"`
	Priority    int64   `json:"priority"`
	Blocked     int64   `json:"blocked"`
	Note        string  `json:"note"`
	ReviewAfter *string `json:"review_after"`
	Today       int64   `json:"today"`
	UpdatedAt   string  `json:"updated_at"`
}

func (q *Queries) UpsertTicketState(ctx context.Context, arg UpsertTicketStateParams) error {
	_, err := q.db.ExecContext(ctx, upsertTicketState,
		arg.TicketID,
		arg.Priority,
		arg.Blocked,
		arg.Note,
		arg.ReviewAfter,
		arg.Today,
		arg.UpdatedAt,
	)
	return err
}
